import os
from os.path import join
import string

pdeFiles = []
extension = ".pde"
dirs = ["/Applications/Processing.app/Contents/Resources/Java/examples"]

for startdir in dirs:
    # walk directory hierarchy, collect paths of pde files into  pdeFiles
    for root, dirs, files in os.walk(startdir):
        #print "Current directory", root
        pdeInDir = [f for f in files if os.path.splitext(f)[1] == extension]
        pdeFiles += [os.path.join(root,f) for f in pdeInDir]

print '//autogenerated by list_pdes.py'
print 'List<String> pdeFiles = new ArrayList<String>();'
for pde in pdeFiles:
    print 'pdeFiles.add("'+pde+'");'