/**
 * 
 */
package test;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;

import junit.framework.TestCase;
import edu.stanford.hci.helpmeout.PdeMatchProcessor;


/**
 * @author bjoern
 * Let's see how the ANTLR PdeLexer works 
 */
public class PdeLexerTest extends TestCase {


	private List<String> pdeFiles ;
	protected void setUp() throws Exception {
		pdeFiles = getPdeList();
	}

	
	
	/** read all processing example files and pass through lexer to make sure we don't ever throw something weird */
	public void testLexAll() throws Exception {
		PdeMatchProcessor proc = new PdeMatchProcessor();
		for(int i=0; i<pdeFiles.size(); i++) {
			
			String fileToOpen = pdeFiles.get(i);
			
			//read file
			BufferedReader in = new BufferedReader(new FileReader(fileToOpen));
			String newProgram="";
			String program="";
			String str;
			while ((str = in.readLine()) != null) {
				program += str+"\n";
			}
			in.close();
			
			//lex and rewrite
			newProgram = proc.process(program);
			
			//make sure we actually got something out of the process
			assertTrue(fileToOpen,(newProgram!=null && newProgram.length()>0) || (program==null) || (program.length()==0));
			
			System.out.println("Processed "+fileToOpen);
		}
	}
	
	public void testLexWeird() throws Exception {
	 //NOTE: Lexer breaks if text ends in comment without new line. hack-fixed in PdeMatchProcessor class
	 String s= "//some\n//comments\nfloat x;\nx++;\n\n////";
	 PdeMatchProcessor proc = new PdeMatchProcessor();
	 String s2 = proc.process(s);
	 System.out.println(s2);
	}
	
	/** read one file from processing example corpus, pass through lexer and print output */
	public void testLexOne() throws Exception {
		
		
		String fileToOpen = pdeFiles.get((int)(Math.random()*pdeFiles.size()));
		BufferedReader in = new BufferedReader(new FileReader(fileToOpen));
		
		String program="";
		String str;
		while ((str = in.readLine()) != null) {
			program += str+"\n";
		}
		in.close();
		PdeMatchProcessor proc = new PdeMatchProcessor();
		System.out.println("Processed "+fileToOpen);
		System.out.println(proc.process(program));
		
	}

	private List<String> getPdeList() {
		//autogenerated by list_pdes.py
		List<String> pdeFiles = new ArrayList<String>();
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Camera/MoveEye/MoveEye.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Camera/OrthoVSPerspective/OrthoVSPerspective.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Camera/Perspective/Perspective.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Form/BrickTower/BrickTower.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Form/BrickTower/Cube.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Form/CubicGrid/CubicGrid.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Form/Icosahedra/Dimension3D.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Form/Icosahedra/Icosahedra.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Form/Icosahedra/Icosahedron.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Form/Icosahedra/Shape3D.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Form/Primitives3D/Primitives3D.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Form/RGBCube/RGBCube.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Form/ShapeTransform/ShapeTransform.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Form/Toroid/Toroid.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Form/Vertices/Vertices.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Image/Explode/Explode.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Image/Extrusion/Extrusion.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Image/Zoom/Zoom.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Lights/Directional/Directional.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Lights/Lights1/Lights1.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Lights/Lights2/Lights2.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Lights/Reflection/Reflection.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Lights/Spot/Spot.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Textures/Texture1/Texture1.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Textures/Texture2/Texture2.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Textures/Texture3/Texture3.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Textures/TextureCube/TextureCube.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Transform/Bird/Bird.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Transform/Birds/Bird.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Transform/Birds/Birds.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Transform/CubesWithinCube/Cube.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Transform/CubesWithinCube/CubesWithinCube.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Transform/PushPopCubes/PushPopCubes.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Transform/Rotate1/Rotate1.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Transform/Rotate2/Rotate2.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Typography/KineticType/KineticType.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Typography/KineticType/Letter.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Typography/KineticType/Line.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Typography/KineticType/Word.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Typography/LetterK/LetterK.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/3D/Typography/Typing/Typing.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Arrays/Array/Array.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Arrays/Array2D/Array2D.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Arrays/ArrayObjects/ArrayObjects.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Color/Brightness/Brightness.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Color/ColorWheel/ColorWheel.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Color/Creating/Creating.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Color/Hue/Hue.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Color/LinearGradient/LinearGradient.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Color/RadialGradient/RadialGradient.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Color/Reading/Reading.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Color/Relativity/Relativity.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Color/Saturation/Saturation.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Color/WaveGradient/WaveGradient.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Control/Conditionals1/Conditionals1.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Control/Conditionals2/Conditionals2.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Control/EmbeddedIteration/EmbeddedIteration.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Control/Iteration/Iteration.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Control/LogicalOperators/LogicalOperators.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Data/CharactersStrings/CharactersStrings.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Data/DatatypeConversion/DatatypeConversion.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Data/IntegersFloats/IntegersFloats.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Data/TrueFalse/TrueFalse.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Data/Variables/Variables.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Data/VariableScope/VariableScope.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Form/Bezier/Bezier.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Form/BezierEllipse/BezierEllipse.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Form/PieChart/PieChart.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Form/PointsLines/PointsLines.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Form/ShapePrimitives/ShapePrimitives.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Form/SimpleCurves/SimpleCurves.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Form/TriangleStrip/TriangleStrip.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Form/Vertices/Vertices.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Image/Alphamask/Alphamask.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Image/BackgroundImage/BackgroundImage.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Image/CreateImage/CreateImage.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Image/LoadDisplayImage/LoadDisplayImage.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Image/Pointillism/Pointillism.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Image/RequestImage/RequestImage.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Image/Sprite/Sprite.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Image/Transparency/Transparency.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Input/Clock/Clock.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Input/Constrain/Constrain.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Input/Easing/Easing.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Input/Keyboard/Keyboard.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Input/KeyboardFunctions/KeyboardFunctions.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Input/Milliseconds/Milliseconds.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Input/Mouse1D/Mouse1D.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Input/Mouse2D/Mouse2D.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Input/MouseFunctions/MouseFunctions.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Input/MousePress/MousePress.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Input/MouseSignals/MouseSignals.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Input/StoringInput/StoringInput.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Math/AdditiveWave/AdditiveWave.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Math/Arctangent/Arctangent.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Math/Distance1D/Distance1D.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Math/Distance2D/Distance2D.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Math/DoubleRandom/DoubleRandom.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Math/Graphing2DEquation/Graphing2DEquation.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Math/IncrementDecrement/IncrementDecrement.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Math/Modulo/Modulo.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Math/Noise1D/Noise1D.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Math/Noise2D/Noise2D.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Math/Noise3D/Noise3D.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Math/NoiseWave/NoiseWave.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Math/OperatorPrecedence/OperatorPrecedence.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Math/PolarToCartesian/PolarToCartesian.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Math/Random/Random.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Math/Sine/Sine.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Math/SineCosine/SineCosine.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Math/SineWave/SineWave.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Objects/CompositeObjects/CompositeObjects.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Objects/Inheritance/Inheritance.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Objects/MultipleConstructors/MultipleConstructors.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Objects/Neighborhood/Neighborhood.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Objects/Objects/Objects.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Shape/DisableStyle/DisableStyle.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Shape/GetChild/GetChild.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Shape/LoadDisplayShape/LoadDisplayShape.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Shape/ScaleShape/ScaleShape.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Structure/Coordinates/Coordinates.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Structure/CreateGraphics/CreateGraphics.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Structure/Functions/Functions.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Structure/Loop/Loop.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Structure/NoLoop/NoLoop.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Structure/Recursion/Recursion.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Structure/Recursion2/Recursion2.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Structure/Redraw/Redraw.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Structure/SetupDraw/SetupDraw.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Structure/StatementsComments/StatementsComments.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Structure/WidthHeight/WidthHeight.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Transform/Arm/Arm.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Transform/Rotate/Rotate.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Transform/Scale/Scale.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Transform/Translate/Translate.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Transform/TriangleFlower/TriangleFlower.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Typography/Letters/Letters.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Typography/Words/Words.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Web/EmbeddedLinks/EmbeddedLinks.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Basics/Web/LoadingImages/LoadingImages.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/DXF Export/SimpleExport/SimpleExport.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/AddListener/AddListener.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/AddListener/Waveform.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/BandPassFilter/BandPassFilter.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/ForwardFFT/ForwardFFT.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/FrequencyEnergy/BeatListener.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/FrequencyEnergy/FrequencyEnergy.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/GetLineIn/GetLineIn.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/GetLineOut/GetLineOut.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/GetMetaData/GetMetaData.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/GetSetPan/GetSetPan.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/GetSetPan/Waveform.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/LinearAverages/LinearAverages.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/LoadFile/LoadFile.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/LoadSample/LoadSample.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/LoadSnippet/LoadSnippet.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/RecordLineIn/RecordLineIn.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/SineWaveSignal/SineWaveSignal.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/UserDefinedEffect/ReverseEffect.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/UserDefinedEffect/UserDefinedEffect.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/UserDefinedSignal/MouseSaw.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Minim (Sound)/UserDefinedSignal/UserDefinedSignal.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Network/CarnivoreClient/CarnivoreClient.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Network/ChatServer/ChatServer.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Network/HTTPClient/HTTPClient.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Network/SharedCanvasClient/SharedCanvasClient.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Network/SharedCanvasServer/SharedCanvasServer.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Network/YahooSearch/YahooSearch.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/OpenGL/Esfera/Esfera.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/OpenGL/ExtrusionGL/ExtrusionGL.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/OpenGL/Geometry/Geometry.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/OpenGL/LightsGL/LightsGL.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/OpenGL/SpaceJunk/Cube.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/OpenGL/SpaceJunk/SpaceJunk.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/OpenGL/TexturedSphere/TexturedSphere.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/OpenGL/Yellowtail/Gesture.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/OpenGL/Yellowtail/Vec3f.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/OpenGL/Yellowtail/Yellowtail.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/PDF Export/Complex3D/Complex3D.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/PDF Export/LargePage/LargePage.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/PDF Export/ManyPages/ManyPages.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/PDF Export/ManyPDFs/ManyPDFs.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/PDF Export/MousePress/MousePress.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/PDF Export/MultipleFrames/MultipleFrames.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/PDF Export/OneFrame/OneFrame.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/PDF Export/RandomBook/RandomBook.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Serial/SerialCallResponse/SerialCallResponse.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Serial/SerialDuplex/SerialDuplex.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Serial/SerialMultiple/SerialMultiple.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Serial/SimpleRead/SimpleRead.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Serial/SimpleWrite/SimpleWrite.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Video (Capture)/AsciiVideo/AsciiVideo.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Video (Capture)/BackgroundSubtraction/BackgroundSubtraction.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Video (Capture)/BrightnessThresholding/BrightnessThresholding.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Video (Capture)/BrightnessTracking/BrightnessTracking.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Video (Capture)/ColorSorting/ColorSorting.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Video (Capture)/ColorSorting/Tuple.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Video (Capture)/FrameDifferencing/FrameDifferencing.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Video (Capture)/Framingham/Framingham.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Video (Capture)/GettingStartedCapture/GettingStartedCapture.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Video (Capture)/HsvSpace/HsvSpace.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Video (Capture)/HsvSpace/Tuple.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Video (Capture)/LivePocky/LivePocky.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Video (Capture)/Mirror/Mirror.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Video (Capture)/Mirror2/Mirror2.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Video (Capture)/RadialPocky/RadialPocky.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Video (Capture)/SlitScan/SlitScan.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Video (Movie)/Loop/Loop.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Video (Movie)/Pixelate/Pixelate.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Libraries/Video (MovieMaker)/DrawingMovie/DrawingMovie.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Advanced Data/ArrayListClass/ArrayListClass.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Advanced Data/ArrayListClass/Ball.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Advanced Data/DirectoryList/DirectoryList.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Advanced Data/HashMapClass/HashMapClass.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Advanced Data/HashMapClass/Word.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Animation/AnimatedSprite/AnimatedSprite.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Animation/AnimatedSprite/Animation.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Animation/Sequential/Sequential.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Cellular Automata/Conway/Conway.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Cellular Automata/Spore1/Spore1.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Cellular Automata/Spore2/Spore2.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Cellular Automata/Wolfram/CA.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Cellular Automata/Wolfram/Wolfram.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Drawing/Animator/Animator.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Drawing/ContinuousLines/ContinuousLines.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Drawing/CustomTool/CustomTool.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Drawing/Pattern/Pattern.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Drawing/Pulses/Pulses.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Drawing/ScribblePlotter/ScribblePlotter.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Effects/FireCube/FireCube.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Effects/Lens/Lens.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Effects/Metaball/Metaball.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Effects/Plasma/Plasma.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Effects/Tunnel/Tunnel.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Effects/UnlimitedSprites/UnlimitedSprites.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Effects/Wormhole/Wormhole.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/File IO/LoadFile1/LoadFile1.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/File IO/LoadFile2/LoadFile2.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/File IO/SaveFile1/SaveFile1.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/File IO/SaveFile2/SaveFile2.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/File IO/SaveManyImages/SaveManyImages.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/File IO/SaveOneImage/SaveOneImage.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/File IO/TileImages/TileImages.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Fractals and L-Systems/Koch/Koch.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Fractals and L-Systems/Mandelbrot/Mandelbrot.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Fractals and L-Systems/PenroseSnowflake/LSystem.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Fractals and L-Systems/PenroseSnowflake/PenroseSnowflake.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Fractals and L-Systems/PenroseSnowflake/PenroseSnowflakeLSystem.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Fractals and L-Systems/PenroseTile/LSystem.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Fractals and L-Systems/PenroseTile/PenroseLSystem.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Fractals and L-Systems/PenroseTile/PenroseTile.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Fractals and L-Systems/Pentigree/LSystem.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Fractals and L-Systems/Pentigree/Pentigree.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Fractals and L-Systems/Pentigree/PentigreeLSystem.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Fractals and L-Systems/Tree/Tree.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/GUI/Button/Button.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/GUI/Buttons/Buttons.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/GUI/Handles/Handles.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/GUI/ImageButton/ImageButton.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/GUI/Rollover/Rollover.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/GUI/Scrollbar/Scrollbar.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Image Processing/Blur/Blur.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Image Processing/Brightness/Brightness.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Image Processing/Convolution/Convolution.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Image Processing/EdgeDetection/EdgeDetection.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Image Processing/Histogram/Histogram.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Image Processing/LinearImage/LinearImage.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Image Processing/PixelArray/PixelArray.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Interaction/Follow1/Follow1.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Interaction/Follow2/Follow2.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Interaction/Follow3/Follow3.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Interaction/Reach1/Reach1.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Interaction/Reach2/Reach2.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Interaction/Reach3/Reach3.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Interaction/Tickle/Tickle.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Motion/Bounce/Bounce.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Motion/BouncyBubbles/BouncyBubbles.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Motion/Brownian/Brownian.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Motion/CircleCollision/Ball.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Motion/CircleCollision/CircleCollision.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Motion/Collision/Collision.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Motion/Linear/Linear.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Motion/MovingOnCurves/MovingOnCurves.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Motion/Puff/Puff.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Motion/Reflection1/Reflection1.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Motion/Reflection2/Ground.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Motion/Reflection2/Orb.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Motion/Reflection2/Reflection2.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Simulate/Chain/Chain.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Simulate/Flocking/Boid.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Simulate/Flocking/Flock.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Simulate/Flocking/Flocking.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Simulate/Fluid/Fluid.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Simulate/MultipleParticleSystems/CrazyParticle.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Simulate/MultipleParticleSystems/MultipleParticleSystems.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Simulate/MultipleParticleSystems/Particle.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Simulate/MultipleParticleSystems/ParticleSystem.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Simulate/SimpleParticleSystem/Particle.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Simulate/SimpleParticleSystem/ParticleSystem.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Simulate/SimpleParticleSystem/SimpleParticleSystem.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Simulate/Smoke/Smoke.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Simulate/SmokeParticleSystem/Particle.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Simulate/SmokeParticleSystem/ParticleSystem.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Simulate/SmokeParticleSystem/SmokeParticleSystem.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Simulate/SoftBody/SoftBody.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Simulate/Spring/Spring.pde");
		pdeFiles.add("/Applications/Processing.app/Contents/Resources/Java/examples/Topics/Simulate/Springs/Springs.pde");
		return pdeFiles;

	}
}
